### ISSUE TITLE
直接下载安卓apk配置的ChatGPT API，无法使用语音是什么问题

### ISSUE THREAD

**Issue by winlone** [worktool/chatgpt-android#2]
![Screenshot_2023-07-09-21-48-47-06_03d01f8820ff180c45a0bcde2da16ed1](https://github.com/worktool/chatgpt-android/assets/73410833/90c3b9de-b3c4-4299-969c-e871e576c990)

**Comment by gallonyin** [comment]
是的，目前讯飞的sdk对接比较麻烦  看后面有没有更好的服务可以接入或替换
